name: Terraform CI
on: [push]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init & Validate
        run: |
          terraform init -backend=false
          terraform validate

      - name: TFLint (Le Linter !)
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Checkov (La Sécurité !)
        run: |
          pip install checkov
          checkov -d .